# Generated by Django 5.1 on 2025-06-27 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siape', '0018_remove_tabulacaocliente_cliente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabulacaocliente',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='tabulacaocliente',
            name='usuario_responsavel',
        ),
        migrations.DeleteModel(
            name='HistoricoTabulacao',
        ),
        migrations.DeleteModel(
            name='TabulacaoCliente',
        ),
    ]
