# Generated by Django 5.1 on 2025-06-20 09:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0010_funcionario_tipo_contrato_entradaauto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradaauto',
            name='data',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='entradaauto',
            name='datahora',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data e Hora'),
        ),
        migrations.AlterField(
            model_name='registropresenca',
            name='datahora',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data e Hora'),
        ),
    ]
