# Generated by Django 5.1 on 2025-06-26 09:06

import apps.funcionarios.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0011_alter_entradaauto_data_alter_entradaauto_datahora_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivofuncionario',
            name='arquivo',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='D:\\vitor\\moneylink_v7\\media\\arquivos_funcionarios'), upload_to=apps.funcionarios.models.get_funcionario_upload_path, verbose_name='Arquivo'),
        ),
    ]
