# Generated by Django 5.1 on 2025-06-09 14:20

import apps.juridico.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juridico', '0002_alter_acoes_recurso_primeiro_grau_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título do Processo')),
                ('numero_processo', models.CharField(blank=True, help_text='Número do processo em decorrimento judicial', max_length=100, null=True, verbose_name='Número do Processo')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_final', models.DateField(blank=True, null=True, verbose_name='Data Final')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('resultado', models.TextField(blank=True, null=True, verbose_name='Resultado')),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo'), ('FINALIZADO', 'Finalizado'), ('ARQUIVADO', 'Arquivado')], default='ATIVO', max_length=20, verbose_name='Status')),
                ('acao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processos', to='juridico.acoes', verbose_name='Ação')),
            ],
            options={
                'verbose_name': 'Processo',
                'verbose_name_plural': 'Processos',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='ArquivosProcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título do Arquivo')),
                ('arquivo', models.FileField(upload_to=apps.juridico.models._upload_to_arquivo_processo, verbose_name='Arquivo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo')], default='ATIVO', max_length=20, verbose_name='Status')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='juridico.processo', verbose_name='Processo')),
            ],
            options={
                'verbose_name': 'Arquivo de Processo',
                'verbose_name_plural': 'Arquivos de Processos',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
