# Generated by Django 5.1 on 2025-06-27 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funcionarios', '0012_alter_arquivofuncionario_arquivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ilha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('titulo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Título')),
                ('quantidade_pas', models.PositiveIntegerField(default=1, verbose_name='Quantidade de PAs')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Ilha',
                'verbose_name_plural': 'Ilhas',
            },
        ),
        migrations.CreateModel(
            name='TipoPeriferico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tipo',
                'verbose_name_plural': 'Periféricos - Tipos',
            },
        ),
        migrations.CreateModel(
            name='Chip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True, verbose_name='Número')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('banido', 'Banido'), ('livre', 'Livre'), ('reutilizado', 'Reutilizado'), ('perdido', 'Perdido'), ('recarregar', 'Recarregar'), ('desativado', 'Desativado')], default='livre', max_length=20, verbose_name='Status')),
                ('data_entrega', models.DateField(blank=True, null=True, verbose_name='Data de Entrega')),
                ('data_criacao_recarga', models.DateField(auto_now_add=True, verbose_name='Data de Criação/Recarga')),
                ('data_banimento', models.DateField(blank=True, null=True, verbose_name='Data de Banimento')),
                ('funcionario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chips_funcionario', to='funcionarios.funcionario', verbose_name='Funcionário')),
                ('setor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chips_setor', to='funcionarios.funcionario', verbose_name='Setor (Funcionário)')),
            ],
            options={
                'verbose_name': 'Chip',
                'verbose_name_plural': 'Chips',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Computador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('condicao', models.CharField(choices=[('novo', 'Novo'), ('antigo', 'Antigo')], default='novo', max_length=20, verbose_name='Condição')),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('em_uso', 'Em Uso'), ('manutencao', 'Em Manutenção'), ('inativo', 'Inativo')], default='disponivel', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('loja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='computadores', to='funcionarios.loja')),
            ],
            options={
                'verbose_name': 'Computador',
                'verbose_name_plural': 'Computadores',
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('senha', models.CharField(max_length=255, verbose_name='Senha')),
                ('status', models.CharField(choices=[('ativo', 'Em uso'), ('inativo', 'sem uso'), ('funcionario_desligado', 'Func desligado'), ('sem_senha', 'Sem senha'), ('sem_recuperacao', 'Sem n° recup'), ('renovado', 'renovado')], default='ativo', max_length=25, verbose_name='Status')),
                ('tipo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo')),
                ('email_recuperacao', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de Recuperação')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('funcionario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emails_funcionario', to='funcionarios.funcionario', verbose_name='Funcionário')),
                ('setor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails_setor', to='funcionarios.funcionario', verbose_name='Setor (Funcionário)')),
            ],
            options={
                'verbose_name': 'Email',
                'verbose_name_plural': 'Emails',
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca')),
                ('tamanho', models.CharField(blank=True, max_length=20, null=True, verbose_name='Tamanho')),
                ('condicao', models.CharField(choices=[('novo', 'Novo'), ('antigo', 'Antigo')], default='novo', max_length=20, verbose_name='Condição')),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('em_uso', 'Em Uso'), ('manutencao', 'Em Manutenção'), ('inativo', 'Inativo')], default='disponivel', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitores', to='funcionarios.loja')),
            ],
            options={
                'verbose_name': 'Monitor',
                'verbose_name_plural': 'Monitores',
            },
        ),
        migrations.CreateModel(
            name='Periferico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True)),
                ('data_aquisicao', models.DateField(blank=True, null=True)),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('em_uso', 'Em Uso'), ('manutencao', 'Em Manutenção'), ('inativo', 'Inativo')], default='disponivel', max_length=20, verbose_name='Status')),
                ('condicao', models.CharField(choices=[('novo', 'Novo'), ('antigo', 'Antigo')], default='novo', max_length=20, verbose_name='Condição')),
                ('estado', models.CharField(choices=[('funcionando', 'Funcionando'), ('com_defeito', 'Com Defeito'), ('em_reparo', 'Em Reparo')], default='funcionando', max_length=20, verbose_name='Estado')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perifericos', to='funcionarios.loja')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ti.tipoperiferico')),
            ],
            options={
                'verbose_name': 'Periférico',
                'verbose_name_plural': 'Periféricos',
            },
        ),
        migrations.CreateModel(
            name='PosicaoAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, verbose_name='Número')),
                ('titulo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Título')),
                ('status', models.CharField(choices=[('livre', 'Livre'), ('ocupada', 'Ocupada'), ('manutencao', 'Em Manutenção'), ('inativa', 'Inativa')], default='livre', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('ilha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posicoes_atendimento', to='ti.ilha')),
            ],
            options={
                'verbose_name': 'PA',
                'verbose_name_plural': 'PAs',
                'ordering': ['ilha', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='AtribuicaoPerifericoPA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_atribuicao', models.DateTimeField()),
                ('data_remocao', models.DateTimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('periferico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ti.periferico')),
                ('posicao_atendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ti.posicaoatendimento')),
            ],
            options={
                'verbose_name': 'Atribuição de Periférico',
                'verbose_name_plural': 'Periféricos - Atribuições',
            },
        ),
        migrations.CreateModel(
            name='AtribuicaoMonitorPA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_atribuicao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Atribuição')),
                ('data_remocao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Remoção')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ti.monitor')),
                ('posicao_atendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ti.posicaoatendimento')),
            ],
            options={
                'verbose_name': 'Atribuição de Monitor',
                'verbose_name_plural': 'Monitores - Atribuições',
            },
        ),
        migrations.CreateModel(
            name='AtribuicaoFuncionarioPA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcionarios.funcionario')),
                ('posicao_atendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ti.posicaoatendimento')),
            ],
            options={
                'verbose_name': 'Atribuição de Funcionário',
                'verbose_name_plural': 'PAs - Atribuições de Funcionários',
            },
        ),
        migrations.CreateModel(
            name='AtribuicaoComputadorPA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_atribuicao', models.DateTimeField(auto_now_add=True)),
                ('data_remocao', models.DateTimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('computador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ti.computador')),
                ('posicao_atendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ti.posicaoatendimento')),
            ],
            options={
                'verbose_name': 'Atribuição de Computador',
                'verbose_name_plural': 'Computadores - Atribuições',
            },
        ),
        migrations.CreateModel(
            name='Ramal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True, verbose_name='Número do Ramal')),
                ('funcionario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ramal_ti', to='funcionarios.funcionario', verbose_name='Funcionário')),
                ('setor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ramais_ti', to='funcionarios.setor', verbose_name='Setor')),
            ],
            options={
                'verbose_name': 'Ramal',
                'verbose_name_plural': 'Ramais',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('titulo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('loja', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salas', to='funcionarios.loja')),
                ('setor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salas_ti', to='funcionarios.setor', verbose_name='Setor')),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
            },
        ),
        migrations.AddField(
            model_name='posicaoatendimento',
            name='sala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ti.sala'),
        ),
        migrations.AddField(
            model_name='ilha',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ilhas', to='ti.sala'),
        ),
        migrations.CreateModel(
            name='CoordenadorSala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('coordenador', 'Coordenador'), ('supervisor', 'Supervisor Geral')], default='coordenador', max_length=20, verbose_name='Tipo')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data de Fim')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordenacao_salas', to='funcionarios.funcionario', verbose_name='Funcionário')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordenadores', to='ti.sala', verbose_name='Sala')),
            ],
            options={
                'verbose_name': 'Coordenador/Supervisor de Sala',
                'verbose_name_plural': 'Coordenadores/Supervisores de Salas',
                'ordering': ['sala__nome', 'funcionario__nome_completo'],
                'unique_together': {('funcionario', 'sala', 'tipo')},
            },
        ),
        migrations.CreateModel(
            name='Sistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acesso', models.CharField(max_length=255, verbose_name='Acesso')),
                ('senha', models.CharField(max_length=255, verbose_name='Senha')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sistema_acessos', to='funcionarios.funcionario', verbose_name='Funcionário')),
            ],
            options={
                'verbose_name': 'Sistema - Acesso',
                'verbose_name_plural': 'Sistema - Acessos',
                'ordering': ['funcionario__nome_completo'],
                'unique_together': {('funcionario', 'acesso')},
            },
        ),
        migrations.CreateModel(
            name='Storm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_administrativo', models.EmailField(max_length=254, verbose_name='E-mail administrativo')),
                ('situacao', models.CharField(choices=[('ativo', 'Ativo'), ('desativado', 'Desativado')], default='ativo', max_length=20, verbose_name='Situação')),
                ('usuario', models.CharField(help_text='Máximo 4 números', max_length=4, verbose_name='Usuário (max 4 números)')),
                ('senha', models.CharField(max_length=255, verbose_name='Senha')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storm_acessos', to='funcionarios.funcionario', verbose_name='Funcionário')),
            ],
            options={
                'verbose_name': 'Storm - Acesso',
                'verbose_name_plural': 'Storm - Acessos',
                'ordering': ['funcionario__nome_completo'],
                'unique_together': {('funcionario', 'usuario')},
            },
        ),
    ]
